In [1]:
from itertools import product
import pandas as pd
import random

In [32]:
characters = ['Anna', 'Babish', 'Charlotte']
places= ['ship','pirate_base','treasure_place']

In [33]:
lists = []
columns = []

columns.append("world_state")
lists.append([0,1,2])

columns.append("pirates_relation")
lists.append([0,1])

columns.append("pirates_power")
lists.append([0,1,2])

columns.append("pirates_treasure")
lists.append([0,1,2])

columns.append("pirates_knows_location_treasure")
lists.append([0,1])

for c in characters:
    columns.append(c+"_power")
    lists.append([0,1])

    columns.append(c+"_injured")
    lists.append([0,1])

    columns.append(c+"_state")
    lists.append([0,2])

    columns.append(c+"_at")
    lists.append(places)

    columns.append(c+"_treasure")
    lists.append([0,1,2,3])

    columns.append(c+"_altruism")
    lists.append([0,1])

    columns.append(c+"_ambition")
    lists.append([0,1])

    columns.append(c+"_knows_location_treasure")
    lists.append([0,1])

    columns.append(c+"_has_access_pirates")
    lists.append([0,1])
   

for p in places:
    columns.append(p+"_distraction")
    lists.append([0,1])

In [34]:
print(columns)

['world_state', 'pirates_relation', 'pirates_power', 'pirates_treasure', 'pirates_knows_location_treasure', 'Anna_power', 'Anna_injured', 'Anna_state', 'Anna_at', 'Anna_treasure', 'Anna_altruism', 'Anna_ambition', 'Anna_knows_location_treasure', 'Anna_has_access_pirates', 'Babish_power', 'Babish_injured', 'Babish_state', 'Babish_at', 'Babish_treasure', 'Babish_altruism', 'Babish_ambition', 'Babish_knows_location_treasure', 'Babish_has_access_pirates', 'Charlotte_power', 'Charlotte_injured', 'Charlotte_state', 'Charlotte_at', 'Charlotte_treasure', 'Charlotte_altruism', 'Charlotte_ambition', 'Charlotte_knows_location_treasure', 'Charlotte_has_access_pirates', 'ship_distraction', 'pirate_base_distraction', 'treasure_place_distraction']

In [9]:
print(lists)

[[0, 1, 2], [0, 1], [0, 1, 2], [0, 1, 2], [0, 1], [0, 1], [0, 1], [0, 2], ['ship', 'pirate_base', 'treasure_place'], [0, 1, 2, 3], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 2], ['ship', 'pirate_base', 'treasure_place'], [0, 1, 2, 3], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 2], ['ship', 'pirate_base', 'treasure_place'], [0, 1, 2, 3], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]

In [10]:


df = pd.DataFrame( columns=columns )
df

Empty DataFrame
Columns: [world_state, pirates_relation, pirates_power, pirates_treasure, pirates_knows_location_treasure, char1_power, char1_injured, char1_state, char1_at, char1_treasure, char1_altruism, char1_ambition, char1_knows_location_treasure, char1_has_access_pirates, char2_power, char2_injured, char2_state, char2_at, char2_treasure, char2_altruism, char2_ambition, char2_knows_location_treasure, char2_has_access_pirates, char3_power, char3_injured, char3_state, char3_at, char3_treasure, char3_altruism, char3_ambition, char3_knows_location_treasure, char3_has_access_pirates, ship_distraction, pirate_base_distraction, treasure_place_distraction]
Index: []

[0 rows x 35 columns]

In [11]:
nb_rows = 50000
for i in range(nb_rows):

    d = []
    for l in lists:
        d.append(random.choice(l))
    df.loc[len(df)] = d

KeyboardInterrupt:

In [48]:
df = pd.read_csv('E:\\Praca_magisterska\\narrative_system\\ship\\rules\\df_actions.csv')

In [49]:
print(df.to_string())

                                                                                                                                                                                                                                                                    actions   char
0  action predictaction_1_travel(char1 : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)=0) ; \n effect: \n at(char1) == ship \n}; \n  char1
1  action predictaction_1_travel(char1 : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)=0) ; \n effect: \n at(char1) == ship \n}; \n  char1
2  action predictaction_1_travel(char1 : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)=0) ; \n effect: \n at(char1) == ship \n}; \n  char1
3  action predictaction_1_travel(char1 : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)=0) ; \n effect: \n at(char1) == ship \n}; \n  char1
4  action predictaction_1_travel(char1 : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)=0) ; \n effect: \n at(char1) == ship \n}; \n  char1

In [50]:
text = "action predictaction_1_travel(char1 : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)==0) ; \n effect: \n at(char1) == ship \n}; \n"

In [51]:
df.actions = text

In [12]:
df = df.drop_duplicates()

In [52]:
df

                                             actions   char
0  action predictaction_1_travel(char1 : characte...  char1
1  action predictaction_1_travel(char1 : characte...  char1
2  action predictaction_1_travel(char1 : characte...  char1
3  action predictaction_1_travel(char1 : characte...  char1
4  action predictaction_1_travel(char1 : characte...  char1

In [53]:
df.to_csv('E:\\Praca_magisterska\\narrative_system\\ship\\rules\\df_actions.csv',index = False)

In [4]:
import random
import pandas as pd

In [61]:
characters = ['Alice', 'Bob', 'Charlie','Sherlock']
civilians = ['Alice', 'Bob', 'Charlie']
items = ['Basketball','Bat']
places= ['HomeB','BasketballCourt','Downtown']
crimes = ['Theft','Murder']

In [28]:
df = pd.read_csv('df_actions.csv')

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
print(df.to_string())

                                                                                                                                                                                                                                                                   actions   char
0  action predictaction_1_travel(char : character){ \n precondition: \nlater(world) & \n( ( at(char1)==treasure_place| at(char1)==pirate_base) |\n( at(char1)==treasure_place| at(char1)==pirate_base)) & \n( ambition(char1)=0) ; \n effect: \n at(char1) == ship \n}; \n  char1

In [68]:
#scenario 1 - Alice!=angry
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '1'}

df1 = pd.DataFrame(pd.np.empty((0, 39)))
for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())
df1.columns =list(state.keys())

C:\Users\kacpe\AppData\Local\Temp\ipykernel_9832\426267497.py:46: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  df1 = pd.DataFrame(pd.np.empty((0, 39)))

In [69]:
#scenario 2 - Bob!=angry
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '2'}


for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())

In [70]:
#scenario 3 - Alice under arrest
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '3'}

df3 = pd.DataFrame(pd.np.empty((0, 39)))
for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())

C:\Users\kacpe\AppData\Local\Temp\ipykernel_9832\564621190.py:46: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  df3 = pd.DataFrame(pd.np.empty((0, 39)))

In [71]:
#scenario 4 - Charlie under arrest
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '4'}


for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())

In [72]:
df1.drop_duplicates(inplace=True)

In [73]:
df1

,scenario,acting_char,Alice_alive,Alice_underArrest,Alice_angry,Alice_suspect,Alice_at,Bob_alive,Bob_underArrest,Bob_angry,...,Theft_Basketball_Downtown_clues,Theft_Bat_HomeB_clues,Theft_Bat_BasketballCourt_clues,Theft_Bat_Downtown_clues,Murder_Basketball_HomeB_clues,Murder_Basketball_BasketballCourt_clues,Murder_Basketball_Downtown_clues,Murder_Bat_HomeB_clues,Murder_Bat_BasketballCourt_clues,Murder_Bat_Downtown_clues
0,1,Alice,1,0,1,2,HomeB,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,Bob,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,Sherlock,1,0,1,2,BasketballCourt,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,Sherlock,1,0,1,2,Downtown,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,Sherlock,1,0,1,2,HomeB,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,4,Sherlock,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
19996,4,Charlie,1,0,1,2,HomeB,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,4,Alice,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
19998,4,Charlie,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
19999,4,Charlie,1,0,1,2,HomeB,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
df1.to_csv('table_training_simple.csv',index = False)