In [18]:
from itertools import product
import pandas as pd
import random

In [19]:
characters = ['Alice', 'Bob', 'Charlie','Sherlock']
items = ['Basketball','Bat']
places= ['HomeB','BasketballCourt','Downtown']
crimes = ['Theft','Murder']

In [20]:
lists = []
columns = []

columns.append("acting_character")
lists.append(characters)

for c in characters:
    columns.append(c+"_alive")
    lists.append([0,1])

    columns.append(c+"_underArrest")
    lists.append([0,1])

    columns.append(c+"_angry")
    lists.append([0,1])

    crimes2 = crimes + ['?','?','?','?','?']
    columns.append(c+"_suspect")
    lists.append(crimes2)

    columns.append(c+"_at")
    lists.append(places)
   
    
for p in places:
    columns.append(p+"_searched")
    lists.append([0,1])


for i in items:
    columns.append(i+"_has")
    lists.append(characters )

for c in crimes:
    for i in items:
        for p in places:
            columns.append(c+"_"+i+"_"+ p +"_clues")
            lists.append([0,0,0,0,0,0,0,0,0,1])

In [21]:
print(lists)

[['Alice', 'Bob', 'Charlie', 'Sherlock'], [0, 1], [0, 1], [0, 1], ['Theft', 'Murder', '?', '?', '?', '?', '?'], ['HomeB', 'BasketballCourt', 'Downtown'], [0, 1], [0, 1], [0, 1], ['Theft', 'Murder', '?', '?', '?', '?', '?'], ['HomeB', 'BasketballCourt', 'Downtown'], [0, 1], [0, 1], [0, 1], ['Theft', 'Murder', '?', '?', '?', '?', '?'], ['HomeB', 'BasketballCourt', 'Downtown'], [0, 1], [0, 1], [0, 1], ['Theft', 'Murder', '?', '?', '?', '?', '?'], ['HomeB', 'BasketballCourt', 'Downtown'], [0, 1], [0, 1], [0, 1], ['Alice', 'Bob', 'Charlie', 'Sherlock'], ['Alice', 'Bob', 'Charlie', 'Sherlock'], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

In [22]:


df = pd.DataFrame( columns=columns )
df

Empty DataFrame
Columns: [acting_character, Alice_alive, Alice_underArrest, Alice_angry, Alice_suspect, Alice_at, Bob_alive, Bob_underArrest, Bob_angry, Bob_suspect, Bob_at, Charlie_alive, Charlie_underArrest, Charlie_angry, Charlie_suspect, Charlie_at, Sherlock_alive, Sherlock_underArrest, Sherlock_angry, Sherlock_suspect, Sherlock_at, HomeB_searched, BasketballCourt_searched, Downtown_searched, Basketball_has, Bat_has, Theft_Basketball_HomeB_clues, Theft_Basketball_BasketballCourt_clues, Theft_Basketball_Downtown_clues, Theft_Bat_HomeB_clues, Theft_Bat_BasketballCourt_clues, Theft_Bat_Downtown_clues, Murder_Basketball_HomeB_clues, Murder_Basketball_BasketballCourt_clues, Murder_Basketball_Downtown_clues, Murder_Bat_HomeB_clues, Murder_Bat_BasketballCourt_clues, Murder_Bat_Downtown_clues]
Index: []

[0 rows x 38 columns]

In [23]:
nb_rows = 50000
for i in range(nb_rows):

    d = []
    for l in lists:
        d.append(random.choice(l))
    df.loc[len(df)] = d

In [32]:
df = df.drop_duplicates()

In [33]:
df

,acting_character,Alice_alive,Alice_underArrest,Alice_angry,Alice_suspect,Alice_at,Bob_alive,Bob_underArrest,Bob_angry,Bob_suspect,...,Theft_Basketball_Downtown_clues,Theft_Bat_HomeB_clues,Theft_Bat_BasketballCourt_clues,Theft_Bat_Downtown_clues,Murder_Basketball_HomeB_clues,Murder_Basketball_BasketballCourt_clues,Murder_Basketball_Downtown_clues,Murder_Bat_HomeB_clues,Murder_Bat_BasketballCourt_clues,Murder_Bat_Downtown_clues
0,Bob,0,1,0,Theft,Downtown,0,1,0,?,...,0,0,0,0,0,0,0,0,0,0
1,Bob,1,0,0,?,Downtown,1,1,1,Theft,...,0,0,0,0,0,0,0,0,0,0
2,Charlie,1,0,1,Theft,HomeB,1,0,1,Murder,...,0,1,0,0,0,0,0,0,0,0
3,Sherlock,0,1,1,?,Downtown,0,1,1,?,...,0,0,0,1,0,1,0,0,1,0
4,Bob,1,1,0,?,HomeB,0,1,0,?,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Sherlock,0,0,0,?,BasketballCourt,0,1,1,Murder,...,0,0,0,0,0,0,0,0,1,0
49996,Sherlock,1,0,1,?,BasketballCourt,0,0,1,?,...,0,0,0,1,0,0,1,0,1,0
49997,Bob,1,1,1,?,Downtown,1,1,1,?,...,0,0,0,0,0,0,0,0,0,0
49998,Charlie,1,0,1,Theft,BasketballCourt,1,0,0,?,...,0,0,0,0,0,0,0,0,0,0
49999,Bob,1,0,1,?,HomeB,0,0,1,?,...,0,1,0,0,0,0,1,1,0,0

In [25]:
df.to_csv('table_training.csv',index = False)

In [4]:
import random
import pandas as pd

In [61]:
characters = ['Alice', 'Bob', 'Charlie','Sherlock']
civilians = ['Alice', 'Bob', 'Charlie']
items = ['Basketball','Bat']
places= ['HomeB','BasketballCourt','Downtown']
crimes = ['Theft','Murder']

In [68]:
#scenario 1 - Alice!=angry
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '1'}

df1 = pd.DataFrame(pd.np.empty((0, 39)))
for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())
df1.columns =list(state.keys())

C:\Users\kacpe\AppData\Local\Temp\ipykernel_9832\426267497.py:46: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  df1 = pd.DataFrame(pd.np.empty((0, 39)))

In [69]:
#scenario 2 - Bob!=angry
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '2'}


for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())

In [70]:
#scenario 3 - Alice under arrest
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '3'}

df3 = pd.DataFrame(pd.np.empty((0, 39)))
for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())

C:\Users\kacpe\AppData\Local\Temp\ipykernel_9832\564621190.py:46: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  df3 = pd.DataFrame(pd.np.empty((0, 39)))

In [71]:
#scenario 4 - Charlie under arrest
basic = ['acting_character',
 'mind_level']
chars_know = ['Alice_alive',
'Alice_underArrest',
'Alice_angry',
'Alice_suspect', 
'Alice_at', 
'Bob_alive',
'Bob_underArrest',
'Bob_angry',
'Bob_suspect',
'Bob_at',
'Charlie_alive',
'Charlie_underArrest',
'Charlie_angry',
'Charlie_suspect',
'Charlie_at',
'Sherlock_alive',
'Sherlock_underArrest',
'Sherlock_angry',
'Sherlock_suspect',
'Sherlock_at',
'HomeB_searched',
'BasketballCourt_searched',
'Downtown_searched',
'Basketball_has',
'Bat_has',
'Theft_Basketball_HomeB_clues',
'Theft_Basketball_BasketballCourt_clues',
'Theft_Basketball_Downtown_clues',
'Theft_Bat_HomeB_clues',
'Theft_Bat_BasketballCourt_clues',
'Theft_Bat_Downtown_clues',
'Murder_Basketball_HomeB_clues',
'Murder_Basketball_BasketballCourt_clues',
'Murder_Basketball_Downtown_clues',
'Murder_Bat_HomeB_clues',
'Murder_Bat_BasketballCourt_clues',
'Murder_Bat_Downtown_clues']

not_character = ['Goal','Real']
character = ['Alice','Bob','Charlie','Sherlock']
state = {'scenario' : '4'}


for n in range(0,5000):
    random_state =  [#alive,underArrest,angry,suspect,       at
                '1','0','1','2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                '1','0',random.randint(0, 1),'2',random.choice(places),
                random.randint(0, 1),random.randint(0, 1),random.randint(0, 1),
                random.choice(civilians),random.choice(civilians),
                '0','0','0','0','0','0','0','0','0','0','0','0']
    state['acting_char'] = random.choice(character)
    for i,know in enumerate(chars_know,0):
   
        state[str(know)] = random_state[i]
            
    
    
    
    df1.loc[len(df1.index)] = list(state.values())

In [72]:
df1.drop_duplicates(inplace=True)

In [73]:
df1

,scenario,acting_char,Alice_alive,Alice_underArrest,Alice_angry,Alice_suspect,Alice_at,Bob_alive,Bob_underArrest,Bob_angry,...,Theft_Basketball_Downtown_clues,Theft_Bat_HomeB_clues,Theft_Bat_BasketballCourt_clues,Theft_Bat_Downtown_clues,Murder_Basketball_HomeB_clues,Murder_Basketball_BasketballCourt_clues,Murder_Basketball_Downtown_clues,Murder_Bat_HomeB_clues,Murder_Bat_BasketballCourt_clues,Murder_Bat_Downtown_clues
0,1,Alice,1,0,1,2,HomeB,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,Bob,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,Sherlock,1,0,1,2,BasketballCourt,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,Sherlock,1,0,1,2,Downtown,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,Sherlock,1,0,1,2,HomeB,1,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,4,Sherlock,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
19996,4,Charlie,1,0,1,2,HomeB,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,4,Alice,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
19998,4,Charlie,1,0,1,2,Downtown,1,0,1,...,0,0,0,0,0,0,0,0,0,0
19999,4,Charlie,1,0,1,2,HomeB,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
df1.to_csv('table_training_simple.csv',index = False)